// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVoIa8k34Lef3ImveFSKI_uihvxGau8eU',
    appId: '1:308684775828:web:f46ce40f69a1b46d3baf81',
    messagingSenderId: '308684775828',
    projectId: 'dasdaily-99697',
    authDomain: 'dasdaily-99697.firebaseapp.com',
    storageBucket: 'dasdaily-99697.firebasestorage.app',
    measurementId: 'G-XBBX0Y7KG3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZDchgSDnKSAaZMTrHjHWK2p1j-rUsAyI',
    appId: '1:308684775828:android:f69b92ce17cca46b3baf81',
    messagingSenderId: '308684775828',
    projectId: 'dasdaily-99697',
    storageBucket: 'dasdaily-99697.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAK-EN55v6n0vYuYmrlxc3bynHPfqDz2w',
    appId: '1:308684775828:ios:6f2e93358561e7ec3baf81',
    messagingSenderId: '308684775828',
    projectId: 'dasdaily-99697',
    storageBucket: 'dasdaily-99697.firebasestorage.app',
    iosBundleId: 'com.example.dasdaily',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAK-EN55v6n0vYuYmrlxc3bynHPfqDz2w',
    appId: '1:308684775828:ios:6f2e93358561e7ec3baf81',
    messagingSenderId: '308684775828',
    projectId: 'dasdaily-99697',
    storageBucket: 'dasdaily-99697.firebasestorage.app',
    iosBundleId: 'com.example.dasdaily',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVoIa8k34Lef3ImveFSKI_uihvxGau8eU',
    appId: '1:308684775828:web:361456aa5ea22fe73baf81',
    messagingSenderId: '308684775828',
    projectId: 'dasdaily-99697',
    authDomain: 'dasdaily-99697.firebaseapp.com',
    storageBucket: 'dasdaily-99697.firebasestorage.app',
    measurementId: 'G-F8NMLP80SF',
  );
}
